import React, { useEffect } from 'react';
import { Shield, FileText, IndianRupee, AlertCircle } from 'lucide-react';
import DynamicSEO from '../components/DynamicSEO';

const TermsPage = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-gray-50 pt-28 pb-20 selection:bg-brand-primary/20">
      <DynamicSEO appTarget="client" pageName="terms" />
      
      <div className="max-w-4xl mx-auto px-4 md:px-8">
        <div className="text-center mb-12">
          <div className="w-16 h-16 bg-brand-primary/10 rounded-full flex items-center justify-center mx-auto mb-6">
            <FileText size={32} className="text-brand-primary" />
          </div>
          <h1 className="text-4xl md:text-5xl font-black text-gray-900 tracking-tight mb-4">Terms and Conditions</h1>
          <p className="text-gray-500 text-lg">Last updated: {new Date().toLocaleDateString('en-IN')}</p>
        </div>

        <div className="bg-white rounded-3xl p-8 md:p-12 shadow-sm border border-gray-100 prose prose-lg max-w-none">
          <p className="lead text-xl text-gray-600 mb-8">
            Welcome to Gomandap. These terms and conditions outline the rules and regulations for the use of Gomandap's Website and Mobile Application, located at gomandap.com. By accessing this website we assume you accept these terms and conditions.
          </p>

          <h2 className="flex items-center gap-2 text-2xl font-bold text-gray-900 mt-12 mb-6">
            <Shield className="text-brand-primary" /> 1. Definitions and Acceptance
          </h2>
          <p>
            "Gomandap", "We", "Our", and "Us" refers to Gomandap Technologies Private Limited. "Client", "You" and "Your" refers to you, the person logging on to this website to book vendors, venues, and event services. "Vendor" refers to third-party event professionals registered on our platform.
          </p>

          <h2 className="flex items-center gap-2 text-2xl font-bold text-gray-900 mt-12 mb-6">
            <IndianRupee className="text-brand-primary" /> 2. Booking, Pricing, and GST
          </h2>
          <ul className="space-y-4 text-gray-600">
            <li><strong>Direct Bookings:</strong> Gomandap acts as an intermediary platform connecting you with event vendors. When you request a quote or confirm a booking, your primary contract is directly with the respective Vendor.</li>
            <li><strong>Pricing Accuracy:</strong> Prices displayed on Gomandap are provided by the Vendors. While we strive for accuracy, the final negotiated price may vary based on your specific customization requests.</li>
            <li><strong>GST (Goods and Services Tax):</strong> As per Indian tax regulations, applicable GST (typically 18% for event services) will be levied on the final invoice generated by the Vendor. It is the Vendor's responsibility to issue a valid GST invoice to you. Gomandap does not collect GST on behalf of vendors unless explicitly stated in a managed-booking tier.</li>
            <li><strong>Platform Fees:</strong> Searching and contacting vendors on Gomandap is free for Clients. We do not charge you hidden convenience fees.</li>
          </ul>

          <h2 className="flex items-center gap-2 text-2xl font-bold text-gray-900 mt-12 mb-6">
            <AlertCircle className="text-brand-primary" /> 3. Cancellations and Refunds
          </h2>
          <p>
            Every Vendor on Gomandap sets their own cancellation and refund policies. You are strongly advised to review the specific Vendor's contract before making any advance payments. Gomandap is not liable for refunds related to Vendor cancellations, no-shows, or sub-standard service, though we maintain a strict quality control standard and may suspend vendors who violate these standards.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-12 mb-6">4. Dispute Resolution</h2>
          <p>
            Any disputes regarding service quality, advance payments, or event execution must be resolved directly between you and the Vendor. Gomandap may offer mediation support at our discretion to ensure a smooth user experience, but we hold no legal liability for vendor performance. All legal disputes are subject to the jurisdiction of the courts in [Your City/State], India.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-12 mb-6">5. User Conduct and Reviews</h2>
          <p>
            You agree to use Gomandap for lawful purposes only. Reviews left on Vendor profiles must be genuine and based on actual service experience. We reserve the right to remove reviews that contain hate speech, explicit content, or are proven to be fraudulent.
          </p>
        </div>
      </div>
    </div>
  );
};

export default TermsPage;
