name: Deploy Scraper to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - 'gomandap-scraper/client/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        working-directory: ./gomandap-scraper/client
        run: npm ci

      - name: Build Scraper Client
        working-directory: ./gomandap-scraper/client
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GOMANDAP_LEADS }}
          projectId: gomandap-leads
          entryPoint: ./gomandap-scraper/client
          channelId: live
